### ISSUE TITLE
Tests not passed in systemd-nswapn container

### ISSUE THREAD

**Issue by tim77** [lunaryorn/gethostname.rs#5]
Full build log:
[build.log](https://github.com/lunaryorn/gethostname.rs/files/3935526/build.log)

Any chance to fix this? Thank you.

**Comment by lunaryorn** [comment]
No, I don't think so; not this way.  Please don't make me dig through a long build log full of unrelated non-Rust stuff from some build tool I don't know about, let alone use.  At _least_ please explain briefly _what_ you did, in particular what command you ran, and take the time to copy the _relevant_ lines from the build log and summarize what's going on.

I mean no offence, but tests pass on Github and right now I don't see what I'm even supposed to fix here.  And, if you permit, I'd like to mention that your way of reporting this issue (you didn't even bother to say hello) doesn't add to my motivation.

Closing as invalid; I'll consider re-opening when you provide what I asked for.

**Comment by tim77** [comment]
Well, at least we have example of how not to report bugs. This usually happens because of rushing, sorry.

> you didn't even bother to say hello

I thought the opposite that this not needed on such places as Github, but i always say this in group chats for example. :)

I fixed this. This was trivial and because of missed `hostname` itself tool. `gethostname.rs` will be in official Fedora repos soon. Sorry for unnecessary noise.

**Comment by lunaryorn** [comment]
Thanks that’s cool news 🙏 I’m happy that you could solve the issue!

 I’m sorry for having been so blunt 😊
